// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGP-IBuwqLwDNrp3ClSMTRcb841V8d4vA',
    appId: '1:562952186970:web:8cd03cc3e75b70322c3c63',
    messagingSenderId: '562952186970',
    projectId: 'meal-mind-3a362',
    authDomain: 'meal-mind-3a362.firebaseapp.com',
    storageBucket: 'meal-mind-3a362.firebasestorage.app',
    measurementId: 'G-C3BYF3WX5J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_i5TTPE4c3LNDTEFzDwEy4Fhu52jPuJE',
    appId: '1:562952186970:android:c3581adf955c2e662c3c63',
    messagingSenderId: '562952186970',
    projectId: 'meal-mind-3a362',
    storageBucket: 'meal-mind-3a362.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI8dRUrebxkxNNL2HJi-AZngCuMoZ2Lek',
    appId: '1:562952186970:ios:f3ae205418596d1d2c3c63',
    messagingSenderId: '562952186970',
    projectId: 'meal-mind-3a362',
    storageBucket: 'meal-mind-3a362.firebasestorage.app',
    iosBundleId: 'com.example.mealMind',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDI8dRUrebxkxNNL2HJi-AZngCuMoZ2Lek',
    appId: '1:562952186970:ios:f3ae205418596d1d2c3c63',
    messagingSenderId: '562952186970',
    projectId: 'meal-mind-3a362',
    storageBucket: 'meal-mind-3a362.firebasestorage.app',
    iosBundleId: 'com.example.mealMind',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGP-IBuwqLwDNrp3ClSMTRcb841V8d4vA',
    appId: '1:562952186970:web:31b8924c29dcd87d2c3c63',
    messagingSenderId: '562952186970',
    projectId: 'meal-mind-3a362',
    authDomain: 'meal-mind-3a362.firebaseapp.com',
    storageBucket: 'meal-mind-3a362.firebasestorage.app',
    measurementId: 'G-1QP0HHMMF0',
  );
}
